# -*- coding: utf-8 -*-
"""9095.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h6tm9a8_Y-RK_GMUAgVtR_xl-tQlplcQ
"""

dp = [0]*13

dp[0] = 0
dp[1] = 1
dp[2] = 2 # 1+1, 2
dp[3] = 4 # 1+1+1, 2+1, 1+2, 3

for i in range(4, 13) :
  dp[i] = dp[i-1] + dp[i-2] + dp[i-3]

t = int(input())
for i in range(t) :
  n = int(input())
  print(dp[n])

